apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "financeservice.fullname" . }}
  labels:
    {{- include "financeservice.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "financeservice.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "financeservice.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if and .Values.workloadIdentity.enabled (eq .Values.workloadIdentity.provider "Azure") }}
        azure.workload.identity/use: "true"
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "financeservice.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if not .Values.database.useInMemoryDatabase }}
      initContainers:
        - name: "{{ .Chart.Name }}-init"
          image: "groundnuty/k8s-wait-for:no-root-v2.0"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "job"
            - '{{ include "financeservice.fullname" . }}-dbdeployment-{{ .Release.Revision }}'
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- $root := . }}
            {{- range $key, $value := .Values.envvariables }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}

            {{- range $ref, $values := .Values.secrets }}
            {{- range $key, $value := $values }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ template "financeservice.fullname" $root }}-{{ $ref | lower }}
                  key: {{ $key }}
            {{- end }}
            {{- end }}            
                  
            - name: ConnectionStrings__FinanceDatabase
              valueFrom:
                secretKeyRef:
                  name: financeservice-database
                  key: ConnectionStrings__FinanceDatabase
            
            - name: FeatureManagement__UseInMemoryDatabase
              value: {{ .Values.database.useInMemoryDatabase | quote }}

            {{- range $key, $value := .Values.observability }}
            {{- if eq $key "serviceName" }}
            - name: Observability__ServiceName
              value: {{ $value | quote }}
            {{- else if eq $key "zipkinExporter" }}
            {{- range $subkey, $subvalue := $value }}
            - name: Observability__ZipkinExporter__{{ $subkey | camelcase }}
              value: {{ $subvalue | quote }}
            {{- end }}
            {{- else if eq $key "otlpExporter" }}
            {{- range $subkey, $subvalue := $value }}
            - name: Observability__OtlpExporter__{{ $subkey | camelcase }}
              value: {{ $subvalue | quote }}
            {{- end }}
            {{- else if eq $key "logLevels" }}
            {{- if $value.default }}
            - name: Observability__LogLevels__Default
              value: {{ $value.default | quote }}
            {{- end }}
            {{- if $value.filters }}
            {{- range $subkey, $subvalue := $value.filters }}
            - name: Observability__LogLevels__Filters__{{ $subkey }}
              value: {{ $subvalue | quote }}
            {{- end }}
            {{- end }}
            {{- else if eq $key "aspNetCoreInstrumentation" }}
            {{- range $subkey, $subvalue := $value }}
            - name: Observability__AspNetCoreInstrumentation__{{ $subkey | camelcase }}
              value: {{ $subvalue | quote }}
            {{- end }}
            {{- else if eq $key "sqlClientInstrumentation" }}
                        {{- range $subkey, $subvalue := $value }}
            - name: Observability__SqlClientInstrumentation__{{ $subkey | camelcase }}
              value: {{ $subvalue | quote }}
            {{- end }}
            {{- else if eq $key "stackExchangeRedisInstrumentation" }}
                                    {{- range $subkey, $subvalue := $value }}
            - name: Observability__StackExchangeRedisInstrumentation__{{ $subkey | camelcase }}
              value: {{ $subvalue | quote }}
            {{- end }}
            {{- else if eq $key "entityFrameworkInstrumentation" }}
                                                {{- range $subkey, $subvalue := $value }}
            - name: Observability__EntityFrameworkInstrumentation__{{ $subkey | camelcase }}
              value: {{ $subvalue | quote }}
            {{- end }}
            {{- else }}
            - name: Observability__{{ $key | camelcase }}
              value: {{ $value | quote }}
              {{- end }}
            {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
