{{- $root := . }}
{{- range $name, $values := .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "financeservice.fullname" $root }}-{{ $name }}
data:
  {{- range $key, $value := $values }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
---
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: financeservice-database
data:
  ConnectionStrings__FinanceDatabase: {{ .Values.database.connectionString | b64enc }}