{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "financeservice.serviceAccountName" . }}
  labels:
    {{- include "financeservice.labels" . | nindent 4 }}

  {{- /* Precompute whether WI is enabled for Azure */}}
  {{- $wiEnabled := and .Values.workloadIdentity.enabled (eq .Values.workloadIdentity.provider "Azure") }}

  {{- if or .Values.serviceAccount.annotations $wiEnabled }}
  annotations:
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

    {{- if $wiEnabled }}
    azure.workload.identity/client-id: "{{ .Values.workloadIdentity.azure.clientId }}"
    {{- with .Values.workloadIdentity.azure.tenantId }}
    azure.workload.identity/tenant-id: "{{ . }}"
    {{- end }}
    {{- end }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
---
{{- if .Values.deployServiceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "financeservice.deployServiceAccountName" . }}
  labels:
    {{- include "financeservice.labels" . | nindent 4 }}

  {{- /* Precompute whether WI is enabled for Azure */}}
  {{- $wiEnabled := and .Values.deployWorkloadIdentity.enabled (eq .Values.deployWorkloadIdentity.provider "Azure") }}

  {{- if or .Values.deployServiceAccount.annotations $wiEnabled }}
  annotations:
    {{- with .Values.deployServiceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

    {{- if $wiEnabled }}
    azure.workload.identity/client-id: "{{ .Values.deployWorkloadIdentity.azure.clientId }}"
    {{- with .Values.deployWorkloadIdentity.azure.tenantId }}
    azure.workload.identity/tenant-id: "{{ . }}"
    {{- end }}
    {{- end }}
  {{- end }}
automountServiceAccountToken: {{ .Values.deployServiceAccount.automount }}
{{- end }}