variables:
- name: kubernetesDeploymentServiceConnection
  value: k8sdemo-deployment
- name: releaseRevision
  value: $[counter(variables['RESOURCES.PIPELINE.CIBUILD.RUNNAME'], 1)]
- name: releaseBuildNumber
  value: $[format('{0}-{1}', variables['RESOURCES.PIPELINE.CIBUILD.RUNNAME'], variables['releaseRevision'])]
- name: artifactVersion
  value: $(RESOURCES.PIPELINE.CIBUILD.RUNNAME)
- name: helmChartArtifactDownloadPath
  value: '$(Pipeline.Workspace)/CIBuild/$(pipelineArtifactName)/$(serviceName)-$(artifactVersion).tgz'
- name: helmChartArtifactValuesFileDownloadPath
  value: '$(Pipeline.Workspace)/CIBuild/$(pipelineArtifactName)/$(stagename)/values.yml'
- name: azureSubscription
  value: '<providedbysecret-sensitivedata>'
- name: azureResourceGroup
  value: '<providedbysecret-sensitivedata>'
- name: azureResourceGroupLocation
  value: '<providedbysecret-sensitivedata>'
- name: aksClusterName
  value: '<providedbysecret-sensitivedata>'
- name: sqlElasticPoolName
  value: '<providedbysecret-sensitivedata>'
- name: sqlServerName
  value: '<providedbysecret-sensitivedata>'