image:
  repository: __azureContainerRegistry__/frontendcustomerorderstatus
  tag: __artifactVersion__

ingress:
  enabled: enabled
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cluster
  hosts:
    - host: customerorderstatus.fastfood.prod.aksdemo.4tecture.ch
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
  - secretName: frontendcustomerorderstatus-tls
    hosts:
      - customerorderstatus.fastfood.prod.aksdemo.4tecture.ch